# Generated by Django 4.1.5 on 2023-01-10 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_zoneid_vitaminstrength_zone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VitaminStrength',
            new_name='SunshineAvailability',
        ),
        migrations.AlterModelTable(
            name='sunshineavailability',
            table='Sunshine_Availability',
        ),
        migrations.AlterModelTable(
            name='zones',
            table='Zones',
        ),
    ]
