# Generated by Django 4.1.5 on 2023-01-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_vitaminstrength_sunshineavailability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipCodes',
            fields=[
                ('zip_code', models.CharField(editable=False, max_length=5, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'zip_codes',
            },
        ),
        migrations.RenameField(
            model_name='sunshineavailability',
            old_name='Strength',
            new_name=' Strength',
        ),
        migrations.RenameField(
            model_name='sunshineavailability',
            old_name='Zone',
            new_name='ZoneId',
        ),
    ]
